# build_installer.ps1
# Compiles GBFRUltrawideSetup.exe with the csc.exe bundled in .NET Framework 4.x,
# and assembles the full release layout under installer\out\ (exe + payload\).
# Usage: powershell -ExecutionPolicy Bypass -File installer\build_installer.ps1 [-Version 0.2.0]
param(
    # Version stamped into the exe (UpdateChecker.CurrentVersion + the assembly's
    # informational version). CI passes the release tag minus the leading 'v'.
    # Local/dev builds default to 0.0.0-dev, which the update check ranks below every
    # real release, so a dev build just shows the newest release as available.
    [string]$Version = '0.0.0-dev'
)

$ErrorActionPreference = 'Stop'

# The version is embedded into a generated C# string literal; restrict it to safe
# characters so a stray quote/backslash cannot break the generated source.
if ($Version -notmatch '^[0-9A-Za-z.+\-]+$') {
    throw "Invalid -Version '$Version' (allowed characters: letters, digits, '.', '-', '+')."
}

$installerDir = Split-Path -Parent $MyInvocation.MyCommand.Path
$repoRoot     = Split-Path -Parent $installerDir
$outDir       = Join-Path $installerDir 'out'
$payloadDir   = Join-Path $outDir 'payload'
$exePath      = Join-Path $outDir 'GBFRUltrawideSetup.exe'

New-Item -ItemType Directory -Force $outDir | Out-Null

# ---- Locate csc.exe (prefer x64, fall back to x86) ----
$cscCandidates = @(
    (Join-Path $env:WINDIR 'Microsoft.NET\Framework64\v4.0.30319\csc.exe'),
    (Join-Path $env:WINDIR 'Microsoft.NET\Framework\v4.0.30319\csc.exe')
)
$csc = $null
foreach ($c in $cscCandidates) {
    if (Test-Path $c) { $csc = $c; break }
}
if ($null -eq $csc) {
    throw 'Could not find .NET Framework csc.exe (v4.0.30319); cannot build.'
}
Write-Host "Using compiler: $csc"

# ---- Stamp the build version ----
# UpdateChecker.CurrentVersion reads VersionInfo.Version from this generated file, so
# the shipped version comes from the build invocation (CI passes the release tag) and
# is never hardcoded in the committed C# sources.
$versionFile = Join-Path $outDir 'VersionInfo.g.cs'
@"
// Generated by build_installer.ps1 - do not edit. The value comes from -Version.
using System.Reflection;

[assembly: AssemblyInformationalVersion("$Version")]

namespace GBFRUltrawideSetup
{
    internal static class VersionInfo
    {
        public const string Version = "$Version";
    }
}
"@ | Out-File -FilePath $versionFile -Encoding utf8
Write-Host "Installer version: $Version"

# ---- Compile ----
# Glob every .cs in installer\ so new source files are picked up automatically
# (avoids the source list drifting out of sync with the CI workflows).
$sources = @(Get-ChildItem -Path (Join-Path $installerDir '*.cs') | ForEach-Object { $_.FullName })
if ($sources.Count -eq 0) { throw "No .cs source files found in $installerDir" }
$sources += $versionFile

$cscArgs = @(
    '/nologo',
    '/target:winexe',
    '/platform:anycpu',
    '/optimize+',
    '/codepage:65001',
    "/win32manifest:$(Join-Path $installerDir 'app.manifest')",
    '/r:System.dll',
    '/r:System.Core.dll',
    '/r:System.Windows.Forms.dll',
    '/r:System.Drawing.dll',
    "/out:$exePath"
) + $sources

& $csc @cscArgs
if ($LASTEXITCODE -ne 0) {
    throw "csc.exe build failed (exit code $LASTEXITCODE)."
}
Write-Host "Build complete: $exePath"

# ---- Assemble payload ----
# payload\ mirrors the game-directory layout: winmm.dll at the root, the GBFRUltrawide.*
# files under scripts\. The installer deploys this tree verbatim, and a manual user can just
# copy the contents of payload\ into their game folder.
$payloadScriptsDir = Join-Path $payloadDir 'scripts'
# Start from a clean payload dir so files from a previous build/layout don't linger.
if (Test-Path $payloadDir) { Remove-Item -Recurse -Force $payloadDir }
New-Item -ItemType Directory -Force $payloadDir | Out-Null
New-Item -ItemType Directory -Force $payloadScriptsDir | Out-Null

# winmm.dll (Ultimate ASI Loader x64) comes from redist\ -> payload\winmm.dll
$winmm = Join-Path $repoRoot 'redist\winmm.dll'
if (Test-Path $winmm) {
    Copy-Item $winmm (Join-Path $payloadDir 'winmm.dll') -Force
    Write-Host 'payload\winmm.dll  <-  redist\winmm.dll'
} else {
    Write-Warning "$winmm not found; payload is missing winmm.dll."
}

# GBFRUltrawide.asi: prefer dist\ (build.ps1 output), otherwise the newest build\ artifact.
# GBFRUltrawide.ini: always taken straight from the repo's ini\ - it is a source file,
# not a build artifact, so the payload snapshot never lags behind the repo wording.
$asiSrc = Join-Path $repoRoot 'dist\GBFRUltrawide.asi'
if (-not (Test-Path $asiSrc)) {
    $found = Get-ChildItem -Path (Join-Path $repoRoot 'build') -Recurse -Filter 'GBFRUltrawide.asi' -ErrorAction SilentlyContinue |
             Sort-Object LastWriteTime -Descending | Select-Object -First 1
    if ($null -ne $found) { $asiSrc = $found.FullName } else { $asiSrc = $null }
}
$payloadPairs = @(
    @{ Name = 'GBFRUltrawide.asi'; Src = $asiSrc },
    @{ Name = 'GBFRUltrawide.ini'; Src = (Join-Path $repoRoot 'ini\GBFRUltrawide.ini') }
)
foreach ($pair in $payloadPairs) {
    if ($null -ne $pair.Src -and (Test-Path $pair.Src)) {
        Copy-Item $pair.Src (Join-Path $payloadScriptsDir $pair.Name) -Force
        Write-Host ("payload\scripts\" + $pair.Name + "  <-  " + $pair.Src)
    } else {
        $note = Join-Path $payloadScriptsDir ($pair.Name + '.MISSING.txt')
        ("This build is missing " + $pair.Name + ". Run build.ps1 in the repo root first, then re-run installer\build_installer.ps1.") |
            Out-File -FilePath $note -Encoding utf8
        Write-Warning ($pair.Name + " not found; placed a note file in payload.")
    }
}

Write-Host ''
Write-Host "Release layout ready: $outDir"
Get-ChildItem -Recurse $outDir | ForEach-Object { Write-Host ('  ' + $_.FullName.Substring($outDir.Length + 1)) }
